# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SimpleAwsCli < Formula
  desc "A simple CLI for common AWS tasks."
  homepage "https://github.com/aws-educate-tw/simple-aws-cli"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aws-educate-tw/simple-aws-cli/releases/download/v0.2.1/simple-aws-cli_0.2.1_darwin_amd64.tar.gz"
      sha256 "42aeab773d34fac7140cf5ad11dd0287f46aa2bd0393527224b4fe717ce68f0b"

      def install
        bin.install "simple-aws-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aws-educate-tw/simple-aws-cli/releases/download/v0.2.1/simple-aws-cli_0.2.1_darwin_arm64.tar.gz"
      sha256 "33d82e6f45a8354f2dadf51eec93c8a53ba3ec2be96efba6e4f571501cf8d65a"

      def install
        bin.install "simple-aws-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/aws-educate-tw/simple-aws-cli/releases/download/v0.2.1/simple-aws-cli_0.2.1_linux_amd64.tar.gz"
      sha256 "fcc7c5f0ddd5cadf04c41482d135695580c03e5fc077dde0487f33e1277e0e87"
      def install
        bin.install "simple-aws-cli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/aws-educate-tw/simple-aws-cli/releases/download/v0.2.1/simple-aws-cli_0.2.1_linux_arm64.tar.gz"
      sha256 "6c96ccf030b39a2cef7979b7ee8111d813a51b02f08e95b34f3e81d4b38f21ae"
      def install
        bin.install "simple-aws-cli"
      end
    end
  end
end
